name: Maven CI
on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        distribution: 'zulu'
   
    - name: Build and test project with Maven
      run: mvn -B package --file pom.xml
 
